name: Build PHP
on:
  workflow_dispatch:
    inputs:
      php-version:
        description: 'PHP version to build'
        required: true
jobs:
  php:
    strategy:
      matrix:
        arch: [x64]
        ts: [ts]
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./php
        with:
          php-version: ${{ github.event.inputs.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}

  artifacts:
    runs-on: ubuntu-latest
    needs: php
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: artifacts
          delete-merged: true
